/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.alumnospracticacongui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maria
 */
public class AlumnosPractica extends javax.swing.JFrame {
    public static DefaultTableModel modelo = new DefaultTableModel();
    public static Alumno veca[]=new Alumno[50];
    public static int n=0;
    
    /**
     * Creates new form AlumnosPractica
     */
    public AlumnosPractica() {
        initComponents();
        setLocationRelativeTo(null);
        String[] titulo = new String[]{"Legajo","Nombre y apellido","D.N.I","Nacionalidad", "E-mail","Direccion","Genero"};
        modelo.setColumnIdentifiers(titulo);
        Datos.setModel(modelo);
        for (int i = 0; i < 50; i++) {
             Alumno a =new Alumno();
             veca[i]=a;
        }
    }
    
    void limp(){
        NyA.setText("");
        Leg.setText("");
        Dni.setText("");
        Nac.setText("");
        Mail.setText(""); 
        Dire.setText("");
        Gen.setText("");
    }
    
    boolean blan(){
        boolean bl; 
        if (NyA.getText().isEmpty() || Leg.getText().isEmpty() || Dni.getText().isEmpty() || Nac.getText().isEmpty() || Mail.getText().isEmpty()|| Dire.getText().isEmpty()|| Gen.getText().isEmpty()) {
            bl=true;
            JOptionPane.showMessageDialog(null, "CAMPOS INCOMPLETOS", "ERROR", 0);
        }else{
            bl=false;
        }
        return bl;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NyA = new javax.swing.JTextField();
        Leg = new javax.swing.JTextField();
        Dni = new javax.swing.JTextField();
        Nac = new javax.swing.JTextField();
        Mail = new javax.swing.JTextField();
        Dire = new javax.swing.JTextField();
        Gen = new javax.swing.JTextField();
        Limp = new javax.swing.JButton();
        Agregar = new javax.swing.JButton();
        Menu = new javax.swing.JButton();
        Random = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Datos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alumnos");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carga de Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre y Apellido:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Legajo");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("D.N.I:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nacionalidad:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("E-Mail:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Direccion:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Genero:");

        NyA.setBackground(new java.awt.Color(255, 255, 255));
        NyA.setForeground(new java.awt.Color(0, 0, 0));
        NyA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NyAKeyPressed(evt);
            }
        });

        Leg.setBackground(new java.awt.Color(255, 255, 255));
        Leg.setForeground(new java.awt.Color(0, 0, 0));
        Leg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LegKeyPressed(evt);
            }
        });

        Dni.setBackground(new java.awt.Color(255, 255, 255));
        Dni.setForeground(new java.awt.Color(0, 0, 0));
        Dni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DniKeyPressed(evt);
            }
        });

        Nac.setBackground(new java.awt.Color(255, 255, 255));
        Nac.setForeground(new java.awt.Color(0, 0, 0));
        Nac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NacKeyPressed(evt);
            }
        });

        Mail.setBackground(new java.awt.Color(255, 255, 255));
        Mail.setForeground(new java.awt.Color(0, 0, 0));

        Dire.setBackground(new java.awt.Color(255, 255, 255));
        Dire.setForeground(new java.awt.Color(0, 0, 0));

        Gen.setBackground(new java.awt.Color(255, 255, 255));
        Gen.setForeground(new java.awt.Color(0, 0, 0));
        Gen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                GenKeyPressed(evt);
            }
        });

        Limp.setBackground(new java.awt.Color(255, 255, 255));
        Limp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Limp.setForeground(new java.awt.Color(0, 0, 0));
        Limp.setText("Limpiar");
        Limp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpActionPerformed(evt);
            }
        });

        Agregar.setBackground(new java.awt.Color(255, 255, 255));
        Agregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Agregar.setForeground(new java.awt.Color(0, 0, 0));
        Agregar.setText("Agregar Alumno");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        Menu.setBackground(new java.awt.Color(204, 255, 255));
        Menu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Menu.setForeground(new java.awt.Color(0, 0, 0));
        Menu.setText("Menu de Opciones");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });

        Random.setBackground(new java.awt.Color(153, 153, 153));
        Random.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Random.setForeground(new java.awt.Color(0, 0, 0));
        Random.setText("Cargar Random");
        Random.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Mail, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Nac, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Dni, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Leg, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NyA, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Gen, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(Dire, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(Random, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                        .addComponent(Limp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Agregar)
                        .addGap(18, 18, 18)
                        .addComponent(Menu)
                        .addGap(25, 25, 25))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(NyA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(Leg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Random))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Nac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Limp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        Datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Datos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void LimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpActionPerformed
        limp();
    }//GEN-LAST:event_LimpActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        if (blan()==false) {
           modelo.addRow(new Object[]{Leg.getText(),NyA.getText(),Dni.getText(),Nac.getText(),Mail.getText(),Dire.getText(),Gen.getText()});
           veca[n].registrarAlumno(Leg.getText(),NyA.getText(),Dni.getText(),Nac.getText(),Mail.getText(),Dire.getText(),Gen.getText());
           n++;
           limp(); 
        }
    }//GEN-LAST:event_AgregarActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        MenuOpciones men = new MenuOpciones();
        men.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuActionPerformed

    private void RandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandomActionPerformed
        int ran1,ran2;
        ran1=(int) Math.floor(Math.random()*2);
        ran2= (int) Math.floor(Math.random()*3);
       
        Mail.setText("Random");
        Dire.setText("Random");
        Dni.setText(Integer.toString((int) (Math.random()*99999999)));
        Leg.setText(Integer.toString((int) (Math.random()*9999)));
        
        switch (ran1) {
            case 0:
                Gen.setText("Masculino");
                switch (ran2) {
                    case 0:
                        NyA.setText("Bob Esponja");
                        Nac.setText("Argentina");
                        break;
                    case 1:
                        NyA.setText("Don Cangrejo");
                        Nac.setText("Uruguaya");
                        break;
                    case 2:
                        NyA.setText("Patricio Estrella");
                        Nac.setText("Chilena");
                        break;
                }
                break;
            case 1:
                Gen.setText("Femenino");
                switch (ran2) {
                    case 0:
                        NyA.setText("Bonbon");
                        Nac.setText("Estadounidense");
                        break;
                    case 1:
                        NyA.setText("Burbuja");
                        Nac.setText("Uruguaya");
                        break;
                    case 2:
                        NyA.setText("Bellota");
                        Nac.setText("Alemana");
                        break;
                }
                break;
        }
    }//GEN-LAST:event_RandomActionPerformed

    private void NyAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NyAKeyPressed
        int t;
        t=evt.getKeyCode();
        if ((t>=evt.VK_A && t<=evt.VK_Z) || t==evt.VK_BACK_SPACE || t==evt.VK_SPACE) {
            NyA.setEditable(true);
        }else{
            NyA.setEditable(false);
        }
    }//GEN-LAST:event_NyAKeyPressed

    private void NacKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NacKeyPressed
        int t;
        t=evt.getKeyCode();
        if ((t>=evt.VK_A && t<=evt.VK_Z) || t==evt.VK_BACK_SPACE) {
            Nac.setEditable(true);
        }else{
            Nac.setEditable(false);
        }
    }//GEN-LAST:event_NacKeyPressed

    private void GenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GenKeyPressed
        int t;
        t=evt.getKeyCode();
        if ((t>=evt.VK_A && t<=evt.VK_Z) || t==evt.VK_BACK_SPACE) {
            Gen.setEditable(true);
        }else{
            Gen.setEditable(false);
        }
    }//GEN-LAST:event_GenKeyPressed

    private void LegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LegKeyPressed
        int t;
        t=evt.getKeyCode();
        if (Leg.getText().length()<5) {
          if ((t>=evt.VK_0 && t<=evt.VK_9) || (t>=evt.VK_NUMPAD0 && t<=evt.VK_NUMPAD9) || t==evt.VK_BACK_SPACE) {
                Leg.setEditable(true);
            }else{
                Leg.setEditable(false);
            }  
        }else{
            if (t==evt.VK_BACK_SPACE) {
                Leg.setEditable(true);
            }else{
                Leg.setEditable(false);
            }
        }
    }//GEN-LAST:event_LegKeyPressed

    private void DniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DniKeyPressed
        int t;
        t=evt.getKeyCode();
        if (Dni.getText().length()<8) {
          if ((t>=evt.VK_0 && t<=evt.VK_9) || (t>=evt.VK_NUMPAD0 && t<=evt.VK_NUMPAD9) || t==evt.VK_BACK_SPACE) {
                Dni.setEditable(true);
            }else{
                Dni.setEditable(false);
            }  
        }else{
            if (t==evt.VK_BACK_SPACE) {
                Dni.setEditable(true);
            }else{
                Dni.setEditable(false);
            }
        }
    }//GEN-LAST:event_DniKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlumnosPractica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlumnosPractica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlumnosPractica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlumnosPractica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlumnosPractica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    public static javax.swing.JTable Datos;
    private javax.swing.JTextField Dire;
    private javax.swing.JTextField Dni;
    private javax.swing.JTextField Gen;
    private javax.swing.JTextField Leg;
    private javax.swing.JButton Limp;
    private javax.swing.JTextField Mail;
    private javax.swing.JButton Menu;
    private javax.swing.JTextField Nac;
    private javax.swing.JTextField NyA;
    private javax.swing.JButton Random;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
