/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.alumnospracticacongui;

import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class ModificarAlu extends javax.swing.JFrame {
     int t;
     TablaMostrarDatos Tmd =new TablaMostrarDatos();
    /**
     * Creates new form ModificarAlu
     */
    public ModificarAlu() {
        initComponents();
        setLocationRelativeTo(null);
        Tmd.setVisible(true);
    }

    void limp(){
        NyA.setText("");
        Leg.setText("");
        Dni.setText("");
        Nac.setText("");
        Mail.setText(""); 
        Dire.setText("");
        Gen.setText("");
    }
    
    boolean blan(){
        boolean bl; 
        if (NyA.getText().isEmpty() || Leg.getText().isEmpty() || Dni.getText().isEmpty() || Nac.getText().isEmpty() || Mail.getText().isEmpty()|| Dire.getText().isEmpty()|| Gen.getText().isEmpty()) {
            bl=true;
            JOptionPane.showMessageDialog(null, "CAMPOS INCOMPLETOS", "ERROR", 0);
        }else{
            bl=false;
        }
        return bl;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NyA = new javax.swing.JTextField();
        Leg = new javax.swing.JTextField();
        Dni = new javax.swing.JTextField();
        Nac = new javax.swing.JTextField();
        Mail = new javax.swing.JTextField();
        Dire = new javax.swing.JTextField();
        Gen = new javax.swing.JTextField();
        Limp = new javax.swing.JButton();
        Agregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificacion de Alumno");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificacion de Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre y Apellido:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Legajo");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("D.N.I:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nacionalidad:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("E-Mail:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Direccion:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Genero:");

        NyA.setBackground(new java.awt.Color(255, 255, 255));
        NyA.setForeground(new java.awt.Color(0, 0, 0));
        NyA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NyAKeyPressed(evt);
            }
        });

        Leg.setBackground(new java.awt.Color(255, 255, 255));
        Leg.setForeground(new java.awt.Color(0, 0, 0));
        Leg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LegKeyPressed(evt);
            }
        });

        Dni.setBackground(new java.awt.Color(255, 255, 255));
        Dni.setForeground(new java.awt.Color(0, 0, 0));
        Dni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DniKeyPressed(evt);
            }
        });

        Nac.setBackground(new java.awt.Color(255, 255, 255));
        Nac.setForeground(new java.awt.Color(0, 0, 0));
        Nac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NacKeyPressed(evt);
            }
        });

        Mail.setBackground(new java.awt.Color(255, 255, 255));
        Mail.setForeground(new java.awt.Color(0, 0, 0));

        Dire.setBackground(new java.awt.Color(255, 255, 255));
        Dire.setForeground(new java.awt.Color(0, 0, 0));

        Gen.setBackground(new java.awt.Color(255, 255, 255));
        Gen.setForeground(new java.awt.Color(0, 0, 0));
        Gen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                GenKeyPressed(evt);
            }
        });

        Limp.setBackground(new java.awt.Color(255, 255, 255));
        Limp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Limp.setForeground(new java.awt.Color(0, 0, 0));
        Limp.setText("Limpiar");
        Limp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpActionPerformed(evt);
            }
        });

        Agregar.setBackground(new java.awt.Color(255, 255, 255));
        Agregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Agregar.setForeground(new java.awt.Color(0, 0, 0));
        Agregar.setText("Modificar Alumno");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Mail, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Nac, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Dni, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Leg, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NyA, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Gen, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Dire, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(Limp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Agregar)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(NyA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(Leg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Nac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Limp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpActionPerformed
        limp();
    }//GEN-LAST:event_LimpActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        if (blan()==false) {
            AlumnosPractica.veca[MenuOpciones.b].registrarAlumno(Leg.getText(),NyA.getText(),Dni.getText(),Nac.getText(),Mail.getText(),Dire.getText(),Gen.getText());
            AlumnosPractica.Datos.setValueAt(Leg.getText(), MenuOpciones.b, 0);
            AlumnosPractica.Datos.setValueAt(NyA.getText(), MenuOpciones.b, 1);
            AlumnosPractica.Datos.setValueAt(Dni.getText(), MenuOpciones.b, 2);
            AlumnosPractica.Datos.setValueAt(Nac.getText(), MenuOpciones.b, 3);
            AlumnosPractica.Datos.setValueAt(Mail.getText(), MenuOpciones.b, 4);
            AlumnosPractica.Datos.setValueAt(Dire.getText(), MenuOpciones.b, 5);
            AlumnosPractica.Datos.setValueAt(Gen.getText(), MenuOpciones.b, 6);
            limp();
            this.setVisible(false);
            Tmd.setVisible(false);
        }
    }//GEN-LAST:event_AgregarActionPerformed

    private void NyAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NyAKeyPressed
        t=evt.getKeyCode();
        if ((t>=evt.VK_A && t<=evt.VK_Z) || t==evt.VK_BACK_SPACE || t==evt.VK_SPACE) {
            NyA.setEditable(true);
        }else{
            NyA.setEditable(false);
        }
    }//GEN-LAST:event_NyAKeyPressed

    private void LegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LegKeyPressed
        t=evt.getKeyCode();
        if (Leg.getText().length()<5) {
          if ((t>=evt.VK_0 && t<=evt.VK_9) || (t>=evt.VK_NUMPAD0 && t<=evt.VK_NUMPAD9) || t==evt.VK_BACK_SPACE) {
                Leg.setEditable(true);
            }else{
                Leg.setEditable(false);
            }  
        }else{
            if (t==evt.VK_BACK_SPACE) {
                Leg.setEditable(true);
            }else{
                Leg.setEditable(false);
            }
        }
    }//GEN-LAST:event_LegKeyPressed

    private void DniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DniKeyPressed
        t=evt.getKeyCode();
        if (Dni.getText().length()<8) {
          if ((t>=evt.VK_0 && t<=evt.VK_9) || (t>=evt.VK_NUMPAD0 && t<=evt.VK_NUMPAD9) || t==evt.VK_BACK_SPACE) {
                Dni.setEditable(true);
            }else{
                Dni.setEditable(false);
            }  
        }else{
            if (t==evt.VK_BACK_SPACE) {
                Dni.setEditable(true);
            }else{
                Dni.setEditable(false);
            }
        }
    }//GEN-LAST:event_DniKeyPressed

    private void NacKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NacKeyPressed
        t=evt.getKeyCode();
        if ((t>=evt.VK_A && t<=evt.VK_Z) || t==evt.VK_BACK_SPACE) {
            Nac.setEditable(true);
        }else{
            Nac.setEditable(false);
        }
    }//GEN-LAST:event_NacKeyPressed

    private void GenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GenKeyPressed
        t=evt.getKeyCode();
        if ((t>=evt.VK_A && t<=evt.VK_Z) || t==evt.VK_BACK_SPACE) {
            Gen.setEditable(true);
        }else{
            Gen.setEditable(false);
        }
    }//GEN-LAST:event_GenKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void MA(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarAlu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarAlu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarAlu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarAlu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarAlu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JTextField Dire;
    private javax.swing.JTextField Dni;
    private javax.swing.JTextField Gen;
    private javax.swing.JTextField Leg;
    private javax.swing.JButton Limp;
    private javax.swing.JTextField Mail;
    private javax.swing.JTextField Nac;
    private javax.swing.JTextField NyA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
