/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.alumnospracticacongui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class TablaMostrarDatos extends javax.swing.JFrame {
    DefaultTableModel data = new DefaultTableModel();
    /**
     * Creates new form TablaMostrarDatos
     */
    public TablaMostrarDatos() {
        initComponents();
        setLocationRelativeTo(null);
        String[] titulo = new String[]{"Legajo","Nombre y apellido","D.N.I","Nacionalidad", "E-mail","Direccion","Genero"};
        data.setColumnIdentifiers(titulo);
        Tab.setModel(data);
    }
    
    private void LimpiarTabla(){
       int fils=Tab.getRowCount();
        for (int i = 0; i < fils; i++) {
                    data.removeRow(0);
                } 
    }
    
    public void TodosDatos (){
        LimpiarTabla();
        for (int i = 0; i < AlumnosPractica.n; i++) {
            data.addRow(new Object[]{AlumnosPractica.veca[i].getLegajo(),AlumnosPractica.veca[i].getNombre_y_apellido(),AlumnosPractica.veca[i].getDni(),AlumnosPractica.veca[i].getNacionalidad(),AlumnosPractica.veca[i].getEmail(),AlumnosPractica.veca[i].getDireccion(),AlumnosPractica.veca[i].getGenero()});
        }
    }
    
    public void NacionalidadDatos (){
        boolean ban=false;
        String na;
        LimpiarTabla();
        na=JOptionPane.showInputDialog(null,"Nacionalidad","Ingrese una Nacionalidad",1);
        for (int i = 0; i < AlumnosPractica.n; i++) {
            if (AlumnosPractica.veca[i].getNacionalidad().compareToIgnoreCase(na)==0) {
                data.addRow(new Object[]{AlumnosPractica.veca[i].getLegajo(),AlumnosPractica.veca[i].getNombre_y_apellido(),AlumnosPractica.veca[i].getDni(),AlumnosPractica.veca[i].getNacionalidad(),AlumnosPractica.veca[i].getEmail(),AlumnosPractica.veca[i].getDireccion(),AlumnosPractica.veca[i].getGenero()});
                ban=true;
            }           
        }
        if (ban==false) {
            JOptionPane.showMessageDialog(null,"La nacionalidad no pudo ser encontrada","NACIONALIDAD INEXISTENTE",0);
            TodosDatos();
        }
    }
    
    public void UnDato(){
        LimpiarTabla();
        data.addRow(new Object[]{AlumnosPractica.veca[MenuOpciones.b].getLegajo(),AlumnosPractica.veca[MenuOpciones.b].getNombre_y_apellido(),AlumnosPractica.veca[MenuOpciones.b].getDni(),AlumnosPractica.veca[MenuOpciones.b].getNacionalidad(),AlumnosPractica.veca[MenuOpciones.b].getEmail(),AlumnosPractica.veca[MenuOpciones.b].getDireccion(),AlumnosPractica.veca[MenuOpciones.b].getGenero()});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tab = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Impresion de datos");
        setResizable(false);

        Tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void tabM(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaMostrarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaMostrarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaMostrarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaMostrarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaMostrarDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tab;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
