
import java.awt.Color;
import java.util.Random;
import java.applet.AudioClip;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

public class Juego extends javax.swing.JFrame {
    public static int intentos = 0;
    public static String nombre = "";
    static Random random = new Random();
    public static int adivinar = random.nextInt(1001);
    
    // Crear un objeto AudioClip y cargar el archivo de sonido
    AudioClip win = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Victoria.wav"));
    
    public Juego() {   
        nombre = JOptionPane.showInputDialog("Por favor, ingresa tu nombre: ");
        initComponents();
        //Esto es para personalizar el spinner para validaciones y que con el enter ingrese el numero en vez de tener que apretar el boton
        JFormattedTextField tf = ((JSpinner.DefaultEditor) Input.getEditor()).getTextField();
        tf.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                int t=evt.getKeyCode();
                //Teclas Invalidas
                if ((t>=evt.VK_A && t<=evt.VK_Z) || t==evt.VK_SPACE) {
                    tf.setEditable(false);
                //El enter para el input
                }else if(t==evt.VK_ENTER){
                    if (!tf.getText().isEmpty()) {
                        chequear();
                    }
                //Teclas validas distintas al enter    
                }else{
                    
                }
            }
        });
        
        setLocationRelativeTo(null);
        Ganaste.setText("");
        Mensaje.setText("");
        Input.setEnabled(true);
        Adivinar.setEnabled(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Input = new javax.swing.JSpinner();
        Mensaje = new javax.swing.JLabel();
        Adivinar = new javax.swing.JButton();
        Intentos = new javax.swing.JLabel();
        VolverMenu = new javax.swing.JButton();
        Ganaste = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adivina el numero!");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        Input.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Input.setEditor(new javax.swing.JSpinner.NumberEditor(Input, ""));
        Input.setValue(1);
        Input.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                InputStateChanged(evt);
            }
        });

        Mensaje.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        Mensaje.setText("Mas bajo!");

        Adivinar.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        Adivinar.setText("Adivinar");
        Adivinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdivinarActionPerformed(evt);
            }
        });

        Intentos.setFont(new java.awt.Font("Tw Cen MT", 0, 48)); // NOI18N
        Intentos.setText("Intentos: 0");

        VolverMenu.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        VolverMenu.setText("Menu Principal");
        VolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuActionPerformed(evt);
            }
        });

        Ganaste.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        Ganaste.setForeground(new java.awt.Color(153, 255, 153));
        Ganaste.setText("Ganaste!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(VolverMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Intentos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(Input, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Adivinar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(Ganaste))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(Mensaje)))
                        .addGap(0, 186, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Ganaste)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Adivinar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Input, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Mensaje)
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VolverMenu)
                    .addComponent(Intentos))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdivinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdivinarActionPerformed
        chequear();
    }//GEN-LAST:event_AdivinarActionPerformed

    private void VolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuActionPerformed
        MenuPrincipal menuPrincipal = new MenuPrincipal();
        menuPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverMenuActionPerformed

    private void InputStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_InputStateChanged
        if ((int)Input.getValue()>1000) {
            Input.setValue(1000);
        }else if((int)Input.getValue()<1){
            Input.setValue(1);
        }
    }//GEN-LAST:event_InputStateChanged

    private void chequear(){
        int intento = (int)Input.getValue();
        if (intento==adivinar) {
            win.play();
            Ganaste.setText("Ganaste "+nombre+"!");
            Input.setEnabled(false);
            Adivinar.setEnabled(false);
        }else if (intento<adivinar) {
            Mensaje.setVisible(true);
            Mensaje.setBackground(Color.orange);
            Mensaje.setText("Mas grande!");
            intentos++;
            Intentos.setText("Intentos: "+intentos);
        }else{
            Mensaje.setVisible(true);
            Mensaje.setBackground(Color.blue);
            Mensaje.setText("Mas chico!");
            intentos++;
            Intentos.setText("Intentos: "+intentos);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adivinar;
    private javax.swing.JLabel Ganaste;
    private javax.swing.JSpinner Input;
    private javax.swing.JLabel Intentos;
    private javax.swing.JLabel Mensaje;
    private javax.swing.JButton VolverMenu;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
